
package application;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
import javax.swing.border.*;

public class Signup extends javax.swing.JFrame {
    
    public static void main(String[] args) {
        new Signup().setVisible(true);}

    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor. d
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        j4 = new javax.swing.JTextField();
        letrehoz = new javax.swing.JButton();
        megsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 44, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Felhasználónév");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Név");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jelszó");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Biztonsági kérdés");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Válasz");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        j1.setBackground(java.awt.Color.lightGray);
        jPanel1.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 236, -1));

        j2.setBackground(java.awt.Color.lightGray);
        jPanel1.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 236, -1));

        j3.setBackground(java.awt.Color.lightGray);
        jPanel1.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 236, -1));

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mi az állatod neve?", "Mi a kedvenc színed?", "Milyen színű a szemed?" }));
        jPanel1.add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 236, -1));

        j4.setBackground(java.awt.Color.lightGray);
        jPanel1.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 236, -1));

        letrehoz.setBackground(new java.awt.Color(41, 44, 53));
        letrehoz.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        letrehoz.setForeground(new java.awt.Color(255, 255, 255));
        letrehoz.setText("Létrehoz");
        letrehoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letrehozActionPerformed(evt);
            }
        });
        jPanel1.add(letrehoz, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 127, 56));

        megsem.setBackground(new java.awt.Color(41, 44, 53));
        megsem.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        megsem.setForeground(new java.awt.Color(255, 0, 0));
        megsem.setText("Mégsem");
        megsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megsemActionPerformed(evt);
            }
        });
        jPanel1.add(megsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 127, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void letrehozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letrehozActionPerformed
      try{
            conn con = new conn();
            
            if(evt.getSource() == letrehoz){
                String sql = "insert into felhasznalo(username, name, password, sec_q, sec_ans) values(?, ?, ?, ?, ?)";
		PreparedStatement st = con.c.prepareStatement(sql);

		st.setString(1, j1.getText());
                st.setString(2, j2.getText());
		st.setString(3, j3.getText());
		st.setString(4, (String) cb.getSelectedItem());
		st.setString(5, j4.getText());

		int i = st.executeUpdate();
		if (i > 0){
                    JOptionPane.showMessageDialog(null, "Létrehozva!");
                    this.setVisible(false);
                    new Login().setVisible(true);
                }               
            }
        
        }catch(Exception e){
            
        }
    
    }//GEN-LAST:event_letrehozActionPerformed
*/
    private void megsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megsemActionPerformed
        if(evt.getSource() == megsem){
                this.setVisible(false);
		new Login().setVisible(true);
    }//GEN-LAST:event_megsemActionPerformed
    }
    
    
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton letrehoz;
    private javax.swing.JButton megsem;
    // End of variables declaration//GEN-END:variables
}
